version: "3"
services:
  go:
    container_name: go
    build:
      context: ./
    volumes:
      - ..:/workspace
    command: sleep infinity 
    networks:
      - app_net
networks:
    app_net:
        external: true